title: Valetudo
description: >-
  Cloud replacement for vacuum robots enabling local-only operation
baseurl: ""
url: https://valetudo.cloud
github_username: Hypfer

plugins:
  - jekyll-seo-tag
collections:
  pages:
    output: true
defaults:
  -
    scope:
      path: ""
      type: "pages"
    values:
      layout: "default"
